apiVersion: v1
kind: ReplicationController
metadata:
  name: cams
spec:
  replicas: 3
  selector:
    app: cams
  template:
    metadata:
      labels:
        app: cams
    spec:
      containers:
      - name: cams
        image: willd/rpi-nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: www
            mountPath: /var/www/html
          - name: logs
            mountPath: /var/log/nginx
      volumes:
       - name: www
         persistentVolumeClaim:
           claimName: webapps-pvc
       - name: logs
         hostPath: 
           path: /tmp/logs
